version: '3.1'
services:
  redis:
    container_name: redis
    hostname: redis
    image: redis:latest
    ports:
      - '6379:6379'
  rcli:
    container_name: rcli
    hostname: rcli
    image: redis:latest
    links:
      - redis
    command: redis-cli -h redis
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8082:8081'
