declare namespace NodeJS {
  export interface ProcessEnv {
    NEXT_PUBLIC_ENVIRONMENT: 'local' | 'dev' | 'qa' | 'production';

    NEXT_PUBLIC_DOMAIN: string;
    NEXT_PUBLIC_CONTENT_DOMAIN: string;
    NEXT_PUBLIC_CONTENT_HOST: string;
    NEXT_PUBLIC_API_HOST: string;
    NEXT_PUBLIC_RECAPTCHA_SITE_KEY: string;

    NEXT_PUBLIC_GOOGLE_CLIENT_ID: string;
    NEXT_PUBLIC_GOOGLE_CLIENT_SECRET: string;

    NEXT_PUBLIC_APPLE_PRIVATE_KEY: string;
    NEXT_PUBLIC_APPLE_TEAM_ID: string;
    NEXT_PUBLIC_APPLE_CLIENT_ID: string;
    NEXT_PUBLIC_APPLE_KEY_ID: string;

    NEXT_PUBLIC_HAVAH_NID: string;
    NEXT_PUBLIC_HAVAH_BLOCKCHAIN_CTZ: string;
    NEXT_PUBLIC_CONTRACT_MINING_RIGHT: string;
    NEXT_PUBLIC_CONTRACT_MZT: string;
    NEXT_PUBLIC_CONTRACT_GOLD_CENTER: string;
    NEXT_PUBLIC_CONTRACT_TREASURY: string;
    NEXT_PUBLIC_TRANSFER_AND_CALL_METHOD: string;

    NEXT_PUBLIC_REDIS_SESSION_HOST: string;
    NEXT_PUBLIC_REDIS_SESSION_PORT: string;
    NEXT_PUBLIC_REDIS_SESSION_DB: string;
    NEXT_PUBLIC_REDIS_SESSION_PASSWORD: string;

    NEXT_PUBLIC_REDIS_MAINTENANCE_HOST: string;
    NEXT_PUBLIC_REDIS_MAINTENANCE_PORT: string;

    NEXT_PUBLIC_WEB_VERSION: string;

    NEXT_PUBLIC_SLACK_WEBHOOK_URL: string;
  }
}
